base_model: deepseek-ai/DeepSeek-R1-Distill-Llama-8B

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
strict: false

hf_use_auth_token: true
datasets:
  - path: patea4/educational-ai-agent
    type: alpaca
    split: train


val_set_size: 0.0
output_dir: ./outputs/out
dataset_prepared_path: last_run_prepared

sequence_len: 8192
sample_packing: true
eval_sample_packing: true

load_in_4bit: false # qlora
load_in_8bit: true # disable for full weights
adapter: lora
lora_r: 16
lora_alpha: 16
lora_dropout: 0.0
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
bias: "none"


gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch_fused
#optimizer: adamw_bnb_8bit
lr_scheduler: linear
learning_rate: 2.0e-4

bf16: true
tf32: true

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 10
flash_attention: true

warmup_steps: 50
evals_per_epoch: 0
saves_per_epoch: 0
weight_decay: 0.01
special_tokens:

train_on_inputs: false
train_on_eos: turn

# save_first_step: true  # uncomment to quickly verify checkpoint saving
